### ISSUE TITLE
Repository request for My Requests component

### ISSUE THREAD

**Issue by jaydeepdeb405** [NowComponents/nowcomponents.github.io#10]
Requesting a new repository to start building My Requests component.

- As a user, I shall be able to view my open requests (pull open request information from the sc_request table).
- The component should show the status of the requests & should update in real-time so that users can see their requests getting processed.

**Comment by dorsy99** [comment]
Hi Jaydeep, 

Thanks for this. I've created https://github.com/NowComponents/ne-my-requests (nowexperience My Requests)

If you are interested in chatting real-time with the other people working on components, join us in SNDevs Slack (http://invite.sndevs.com/) and join the #Hacktoberfest channel :) We'd love to meet you.
