### ISSUE TITLE
Component to get your Paypal order information

### ISSUE THREAD

**Issue by 23Thom** [NowComponents/nowcomponents.github.io#16]
Hi :) 
I would like to share my component were you can enter a Paypal order number and then you get some order informations. I used axios to do some external API calls. :)
Thanks!

**Comment by dorsy99** [comment]
Hey @23Thom - I've created https://github.com/NowComponents/paypal-order for you :)

**Comment by 23Thom** [comment]
Thanks a lot😊👍🏻
